/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mrudy
 */
public class KonversiSuhu extends javax.swing.JFrame {

    /**
     * Creates new form KonversiSuhu
     */
    public Double input;
    public Double celcius;
    public Double fahrenheit;
    public Double reamur;
    public Double calvin;
    public String hasilcelcius;
    public String hasilfahrenheit;
    public String hasilreamur;
    public String hasilcalvin;
    
    public KonversiSuhu() {
        initComponents();
    }
    
    
    
    /*private*/
    private void celcius() {
        input=Double.parseDouble(SuhuAwal.getText());
        
        celcius=input;
        fahrenheit=celcius*1.8+32;
        reamur=celcius*0.8;
        calvin=celcius+273.15;
        
        hasilcelcius=Double.toString(celcius);
        txtcelcius.setText(hasilcelcius);
        
        hasilfahrenheit=Double.toString(fahrenheit);
        txtfahrenheit.setText(hasilfahrenheit);
        
        hasilreamur=Double.toString(reamur);
        txtreamur.setText(hasilreamur);
        
        hasilcalvin=Double.toString(calvin);
        txtcalvin.setText(hasilcalvin);
        
    }
    
    private void  fahrenheit(){
    input  = Double.parseDouble(SuhuAwal.getText());
    
    fahrenheit=input;
    celcius=(fahrenheit-32)/1.8;
    reamur=(fahrenheit-32)/2.25;
    
   hasilcelcius=Double.toString(celcius);
        txtcelcius.setText(hasilcelcius);
        
        hasilfahrenheit=Double.toString(fahrenheit);
        txtfahrenheit.setText(hasilfahrenheit);
        
        hasilreamur=Double.toString(reamur);
        txtreamur.setText(hasilreamur);
        
        hasilcalvin=Double.toString(calvin);
        txtcalvin.setText(hasilcalvin);
            
    }
    
    private void reamur() {
    input = Double.parseDouble(SuhuAwal.getText());
      reamur=input;
      celcius=reamur/0.8;
      fahrenheit=(reamur*2.25)+32;
      calvin=reamur/0.8+237.15;
      
     hasilcelcius=Double.toString(celcius);
        txtcelcius.setText(hasilcelcius);
        
        hasilfahrenheit=Double.toString(fahrenheit);
        txtfahrenheit.setText(hasilfahrenheit);
        
        hasilreamur=Double.toString(reamur);
        txtreamur.setText(hasilreamur);
        
        hasilcalvin=Double.toString(calvin);
        txtcalvin.setText(hasilcalvin);
           
    }
    
    private void calvin() {
    input=Double.parseDouble(SuhuAwal.getText());
       
       calvin=input;
       celcius=calvin-273.15;
       fahrenheit=calvin*1.8-459.67;
       reamur=(calvin-237.15)*0.8;
       
     hasilcelcius=Double.toString(celcius);
        txtcelcius.setText(hasilcelcius);
        
        hasilfahrenheit=Double.toString(fahrenheit);
        txtfahrenheit.setText(hasilfahrenheit);
        
        hasilreamur=Double.toString(reamur);
        txtreamur.setText(hasilreamur);
        
        hasilcalvin=Double.toString(calvin);
        txtcalvin.setText(hasilcalvin);
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SuhuAwal2 = new javax.swing.JLabel();
        SuhuAwal = new javax.swing.JTextField();
        Celcius = new javax.swing.JRadioButton();
        Fahrenheit = new javax.swing.JRadioButton();
        Reamur = new javax.swing.JRadioButton();
        Calvin = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtcelcius = new javax.swing.JTextField();
        txtfahrenheit = new javax.swing.JTextField();
        txtreamur = new javax.swing.JTextField();
        txtcalvin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SuhuAwal2.setText("Suhu Awal");

        Celcius.setText("Celcius");

        Fahrenheit.setText("Fahrenheit");

        Reamur.setText("Reamur");

        Calvin.setText("Calvin");

        jLabel2.setText("Celcius");

        jLabel3.setText("Fahrenheit");

        jLabel4.setText("Reamur");

        jLabel5.setText("Calvin");

        jButton1.setText("Result");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtcalvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcalvinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Celcius, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Fahrenheit, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(Reamur, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Calvin, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtcalvin, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                    .addComponent(txtreamur)
                                    .addComponent(txtfahrenheit)
                                    .addComponent(txtcelcius))))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(SuhuAwal2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(SuhuAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SuhuAwal2)
                    .addComponent(SuhuAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Celcius)
                    .addComponent(Fahrenheit)
                    .addComponent(Reamur)
                    .addComponent(Calvin))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcelcius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtfahrenheit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtreamur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtcalvin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcalvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcalvinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcalvinActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if (Celcius.isSelected()){
            celcius();
        }
        else if (Fahrenheit.isSelected()){
            fahrenheit();
        }
        else if (Reamur.isSelected()) {
            reamur();
        }
        else if (Calvin.isSelected()) {
            calvin();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Calvin;
    private javax.swing.JRadioButton Celcius;
    private javax.swing.JRadioButton Fahrenheit;
    private javax.swing.JRadioButton Reamur;
    private javax.swing.JTextField SuhuAwal;
    private javax.swing.JLabel SuhuAwal2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtcalvin;
    private javax.swing.JTextField txtcelcius;
    private javax.swing.JTextField txtfahrenheit;
    private javax.swing.JTextField txtreamur;
    // End of variables declaration//GEN-END:variables

    
}
